Fix logging for long filename | Remove awk and tail dependency
* Fix updating from script

diff --git a/gdl b/gdl
--- a/gdl
+++ b/gdl
@@ -14,7 +14,7 @@ Options:\n
   -v | --verbose - Display detailed message (only for non-parallel uploads).\n
   -V | --verbose-progress - Display detailed message and detailed upload progress(only for non-parallel uploads).\n
   -D | --debug - Display script command trace.\n
-  -U | --update - Update gdrive downloader.\n
+  -u | --update - Update gdrive downloader.\n
   -h | --help - Display usage instructions.\n\n" "${0##*/}"
     exit 0
 }
@@ -40,11 +40,15 @@ bashSleep() {
     read -rt "$1" <> <(:) || :
 }
 
+# Usage: tail "n" < "file" or <<< "$varible" or pipe some output
+tail() {
+    mapfile -tn 0 line
+    printf '%s\n' "${line[@]: -$1}"
+}
+
 # Move cursor to nth no. of line and clear it to the begining.
 clearLine() {
-    if isTerminal; then
-        printf "\033[%sA\033[2K" "$1"
-    fi
+    printf "\033[%sA\033[2K" "$1"
 }
 
 # Remove array duplicates, maintain the order as original.
@@ -61,30 +65,40 @@ removeArrayDuplicates() {
 }
 
 # Print a text to center interactively and fill the rest of the line with text specified.
+# This function is fine-tuned to this script functionality, so may appear unusual.
 # https://gist.github.com/TrinityCoder/911059c83e5f7a351b785921cf7ecda
 printCenter() {
-    [[ $# = 0 ]] && printf "%s: Missing arguments\n" "${FUNCNAME[0]}" && return 1
+    [[ $# -lt 3 ]] && printf "%s: Missing arguments\n" "${FUNCNAME[0]}" && return 1
     declare -i TERM_COLS="$COLUMNS"
+    declare type="$1" filler
+    case "$type" in
+        normal)
+            declare out="$2" && symbol="$3"
+            ;;
+        justify)
+            if [[ $# = 3 ]]; then
+                declare input1="$2" symbol="$3" TO_PRINT out
+                TO_PRINT="$((TERM_COLS * 93 / 100))"
+                { [[ ${#input1} -gt ${TO_PRINT} ]] && out="[ ${input1:0:TO_PRINT}.. ]"; } || { out="[ $input1 ]"; }
+            else
+                declare input1="$2" input2="$3" symbol="$4" TO_PRINT temp out
+                TO_PRINT="$((TERM_COLS * 40 / 100))"
+                { [[ ${#input1} -gt ${TO_PRINT} ]] && temp+=" ${input1:0:TO_PRINT}.."; } || { temp+=" $input1"; }
+                TO_PRINT="$((TERM_COLS * 55 / 100))"
+                { [[ ${#input2} -gt ${TO_PRINT} ]] && temp+="${input2:0:TO_PRINT}.. "; } || { temp+="$input2 "; }
+                out="[$temp]"
+            fi
+            ;;
+        *) return 1 ;;
+    esac
 
-    if [[ -z $3 ]]; then
-        declare out="$1" && sym="$2"
-    else
-        declare out="[ $1 ]" && outt="$1"
-        TO_PRINT="$((TERM_COLS * 87 / 100))"
-        if [[ ${#outt} -gt ${TO_PRINT} ]]; then
-            outt="${1:0:TO_PRINT}.." && out="[ $outt ]" && unset sym
-        else
-            declare sym="$2"
-        fi
-    fi
     declare -i str_len=${#out}
-    [[ $str_len -ge $TERM_COLS ]] && {
+    [[ $str_len -ge $(((TERM_COLS - 1))) ]] && {
         printf "%s\n" "$out" && return 0
     }
 
     declare -i filler_len="$(((TERM_COLS - str_len) / 2))"
-    [[ $# -ge 2 ]] && ch="${sym:0:1}" || ch=" "
-    filler=""
+    [[ $# -ge 2 ]] && ch="${symbol:0:1}" || ch=" "
     for ((i = 0; i < filler_len; i++)); do
         filler="${filler}${ch}"
     done
@@ -124,10 +138,16 @@ extractID() {
     printf "%s\n" "$ID"
 }
 
-# Calculation of file in readable form from bytes.
-# https://unix.stackexchange.com/a/374877
-calcSize() {
-    awk '{ split( "B KB MB GB TB PB" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } printf "%.2f %s", $1, v[s] }'
+# Convert bytes to human readable form, pure bash.
+# https://unix.stackexchange.com/a/259254
+bytesToHuman() {
+    declare b=${1:-0} d='' s=0 S=(Bytes {K,M,G,T,P,E,Y,Z}B)
+    while ((b > 1024)); do
+        d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
+        b=$((b / 1024))
+        ((s++))
+    done
+    printf "%s\n" "$b$d ${S[$s]}"
 }
 
 # Default wget command used everywhere
@@ -146,29 +166,30 @@ curlFetch() {
 
 # Fetch the latest script and update.
 update() {
+    declare REPO="gdrive-downloader"
     printf "Fetching update script.. \n"
-    curl -s https://raw.githubusercontent.com/Akianonymus/""$REPO""/master/update_gdl | bash
+    curl -s https://raw.githubusercontent.com/Akianonymus/"""$REPO"""/master/update_gdl | bash
     exit 0
 }
 
 # Check if the file ID exists and determine it's type [ folder | Files ], otherwise exit the script.
 checkID() {
     [[ $# = 0 ]] && printf "%s: Missing arguments\n" "${FUNCNAME[0]}" && return 1
-    printCenter "[ Validating URL.. ]" "="
+    printCenter "justify" "Validating URL.." "-"
     declare ID="$1" KEY="$2" STATUS ERRORCODE
     STATUS="$(curlFetch """$API_URL""/drive/""$API_VERSION""/files/""$ID""?alt=json&fields=mimeType&key=""$KEY""")"
     ERRORCODE="$(jsonValue code <<< "$STATUS")"
     if [[ -z $ERRORCODE ]]; then
-        clearLine 1 && printCenter "[ Valid URL/ID, determining type.. ]" "="
+        clearLine 1 && printCenter "justify" "Valid URL/ID" ", determining type.." "-"
         if [[ $STATUS =~ folder ]]; then
             FOLDERID="$ID"
-            for _ in {1..2}; do clearLine 1; done && printCenter "[ Folder Detected ]" "=" && printf "\n"
+            for _ in {1..2}; do clearLine 1; done && printCenter "justify" "Folder Detected" "=" && newLine "\n"
         else
             FILEID="$ID"
-            for _ in {1..2}; do clearLine 1; done && printCenter "[ File Detected ]" "=" && printf "\n"
+            for _ in {1..2}; do clearLine 1; done && printCenter "justify" "File Detected" "=" && newLine "\n"
         fi
     else
-        for _ in {1..2}; do clearLine 1; done && printf "\n" && printCenter "[ Invalid URL/ID ]" "=" && printf "\n"
+        for _ in {1..2}; do clearLine 1; done && newLine "\n" && printCenter "justify" "Invalid URL/ID" "=" && newLine "\n"
         return 1
     fi
 
@@ -178,45 +199,45 @@ checkID() {
 downloadFile() {
     [[ $# -lt 2 ]] && printf "%s: Missing arguments\n" "${FUNCNAME[0]}" && return 1
     declare FILEID="$1" KEY="$2" PARALLEL="$3"
-    [[ -z "$PARALLEL" ]] && printCenter "[ Fetching file metadata.. ]" "="
+    [[ -z "$PARALLEL" ]] && printCenter "justify" "Fetching file metadata.." "-"
     declare INFO NAME SERVER_SIZE
     INFO="$(curlFetch """$API_URL""/drive/""$API_VERSION""/files/""$FILEID""?alt=json&fields=name,size&key=""$KEY""")"
     NAME="$(jsonValue name <<< "$INFO")"
     if [[ -n $NAME ]]; then
         SERVER_SIZE="$(jsonValue size <<< "$INFO")"
-        SERVER_SIZE_READABLE="$(calcSize <<< "$SERVER_SIZE")"
+        SERVER_SIZE_READABLE="$(bytesToHuman "$SERVER_SIZE")"
 
-        [[ -z "$PARALLEL" ]] && clearLine 1 && printCenter "$NAME | $SERVER_SIZE_READABLE" "=" justify
+        [[ -z "$PARALLEL" ]] && clearLine 1 && printCenter "justify" "$NAME" " | $SERVER_SIZE_READABLE" "="
 
-        URL="""$API_URL""/drive/""$API_VERSION""/files/""$FILEID""?alt=media&key=""$KEY"""
+        # URL="""$API_URL""/drive/""$API_VERSION""/files/""$FILEID""?alt=media&key=""$KEY""" ( downloading with api )
 
         if [[ -f "$NAME" ]]; then
             declare LOCAL_SIZE && LOCAL_SIZE="$(wc -c < "$NAME")"
 
             if [[ $LOCAL_SIZE = "$SERVER_SIZE" ]]; then
-                printCenter "[ File already present ]" "=" && [[ -z "$PARALLEL" ]] && printf "\n"
+                printCenter "justify" "File already present" "=" && [[ -z "$PARALLEL" ]] && newLine "\n"
             else
-                [[ -z "$PARALLEL" ]] && printCenter "[ File is partially present, resuming.. ]" "="
+                [[ -z "$PARALLEL" ]] && printCenter "justify" "File is partially" " present, resuming.." "-"
                 wget -q --save-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=$FILEID"
                 if [[ -z "$PARALLEL" ]]; then
-                    download -c --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(tail -1 "$TMPFILE"COOKIE | sed 's/\s\+/\n/g' | tail -1)"
+                    download -c --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(: "$(tail 1 < "$TMPFILE"COOKIE)" && : "${_//$'\t'/$'\n'}" && tail 1 <<< "$_")"
                 else
-                    wget -c -q --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(tail -1 "$TMPFILE"COOKIE | sed 's/\s\+/\n/g' | tail -1)"
+                    wget -c -q --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(: "$(tail 1 < "$TMPFILE"COOKIE)" && : "${_//$'\t'/$'\n'}" && tail 1 <<< "$_")"
                 fi
                 [[ -z "$PARALLEL" ]] && for _ in {1..2}; do clearLine 1; done
-                printCenter "[ Downloaded ]" "=" && [[ -z "$PARALLEL" ]] && printf "\n"
+                printCenter "justify" "Downloaded" "=" && [[ -z "$PARALLEL" ]] && newLine "\n"
             fi
         else
-            [[ -z "$PARALLEL" ]] && printCenter "[ Downloading file.. ]" "="
+            [[ -z "$PARALLEL" ]] && printCenter "justify" "Downloading file.." "-"
 
             wget -q --save-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=$FILEID"
             if [[ -z "$PARALLEL" ]]; then
-                download --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(tail -1 "$TMPFILE"COOKIE | sed 's/\s\+/\n/g' | tail -1)"
+                download --load-cookies "$TMPFILE"COKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(: "$(tail 1 < "$TMPFILE"COOKIE)" && : "${_//$'\t'/$'\n'}" && tail 1 <<< "$_")"
             else
-                wget -q --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(tail -1 "$TMPFILE"COOKIE | sed 's/\s\+/\n/g' | tail -1)"
+                wget -q --load-cookies "$TMPFILE"COOKIE -O ./"$NAME" "https://drive.google.com/uc?export=download&id=""$FILEID""&confirm=$(: "$(tail 1 < "$TMPFILE"COOKIE)" && : "${_//$'\t'/$'\n'}" && tail 1 <<< "$_")"
             fi
             [[ -z "$PARALLEL" ]] && for _ in {1..2}; do clearLine 1; done
-            printCenter "[ Downloaded ]" "=" && [[ -z "$PARALLEL" ]] && printf "\n"
+            printCenter "justify" "Downloaded" "=" && [[ -z "$PARALLEL" ]] && newLine "\n"
         fi
         if [[ -n $LOG_FILE_ID && ! -d $LOG_FILE_ID ]]; then
             # shellcheck disable=SC2129
@@ -225,12 +246,11 @@ downloadFile() {
                 printf "%s\n" "Name: $NAME"
                 printf "%s\n" "Size: $SERVER_SIZE_READABLE"
                 printf "%s\n" "ID: $FILEID"
-
                 printf '\n'
             } >> "$LOG_FILE_ID"
         fi
     else
-        printCenter "[ Failed, some unknown error ]" "=" 1>&2
+        printCenter "justify" "Failed" ", some unknown error." "=" 1>&2
         DOWNLOAD_STATUS=ERROR && export DOWNLOAD_STATUS # Send a error status, used in folder downloads.
         [[ -z "$PARALLEL" ]] && printf "%s\n" "$INFO"
     fi
@@ -241,18 +261,18 @@ downloadFolder() {
     [[ $# = 0 ]] && printf "%s: Missing arguments\n" "${FUNCNAME[0]}" && return 1
     declare FOLDERID="$1" KEY="$2" parallel="$3" ERROR_STATUS=0 SUCCESS_STATUS=0
     declare NAME FILES=() FOLDERS=()
-    printCenter "[ Fetching folder details.. ]" "="
+    printCenter "justify" "Fetching folder details.." "-"
     NAME="$(jsonValue name <<< "$(curlFetch """$API_URL""/drive/""$API_VERSION""/files/""$FOLDERID""?alt=json&fields=name&key=""$KEY""")")"
     if [[ -n $NAME ]]; then
-        printf '\n'
-        printCenter "$NAME" "=" justify
+        newLine "\n"
+        printCenter "justify" "$NAME" "="
         INFO="$(curlFetch """$API_URL""/drive/""$API_VERSION""/files?q=%27""$FOLDERID""%27+in+parents&fields=files(id,mimeType)&key=""$KEY""")"
 
         mapfile -t FILES <<< "$(jsonValue id <<< "$(grep -v folder <<< "$INFO" | grep mimeType -B1)")"
         mapfile -t FOLDERS <<< "$(jsonValue id <<< "$(grep folder -B1 <<< "$INFO")")"
-        [[ -z ${FILES[*]} && -z ${FOLDERS[*]} ]] && for _ in {1..3}; do clearLine 1; done && printCenter "[ $NAME | Empty Folder ]" "=" && printf "\n" && return 0
+        [[ -z ${FILES[*]} && -z ${FOLDERS[*]} ]] && for _ in {1..3}; do clearLine 1; done && printCenter "justify" "$NAME" " | Empty Folder" "=" && newLine "\n" && return 0
         for _ in {1..3}; do clearLine 1; done
-        printCenter "[ $NAME | ""${#FILES[@]}"" Files | ""${#FOLDERS[@]}"" sub-folders ]" "=" && printf "\n\n"
+        printCenter "justify" "$NAME" "| ""${#FILES[@]}"" Files | ""${#FOLDERS[@]}"" sub-folders" "=" && newLine "\n\n"
 
         if [[ -f $NAME ]]; then
             NAME="$NAME$RANDOM"
@@ -271,7 +291,7 @@ downloadFolder() {
                 else
                     NO_OF_PARALLEL_JOBS_FINAL="$NO_OF_PARALLEL_JOBS"
                 fi
-                export -f printCenter jsonValue download clearLine calcSize downloadFile curlFetch
+                export -f printCenter jsonValue download clearLine bytesToHuman downloadFile curlFetch
                 export KEY COLUMNS LOG_FILE_ID SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_UPLOAD API_URL API_VERSION
                 # shellcheck disable=SC2016
                 printf "%s\n" "${FILES[@]}" | xargs -n1 -P"$NO_OF_PARALLEL_JOBS_FINAL" -i bash -c '
@@ -284,12 +304,12 @@ downloadFolder() {
                     SUCCESS_STATUS="$(count < "$TMPFILE"SUCCESS)"
                     ERROR_STATUS="$(count < "$TMPFILE"ERROR)"
                     bashSleep 1 && clearLine 1
-                    printCenter "[ Status: ""$SUCCESS_STATUS"" Downloaded | ""$ERROR_STATUS"" FAILED ]" "="
+                    printCenter "justify" "Status" ": ""$SUCCESS_STATUS"" Downloaded | ""$ERROR_STATUS"" Failed" "="
                     if [[ $(((SUCCESS_STATUS + ERROR_STATUS))) = "${#FILES[@]}" ]]; then
                         clearLine 1 && break
                     fi
                 done
-                printf "\n"
+                newLine "\n"
             else
                 for i in "${FILES[@]}"; do
                     downloadFile "$i" "$KEY"
@@ -297,16 +317,16 @@ downloadFolder() {
                     if ! [[ $VERBOSE = true || $VERBOSE_PROGRESS = true ]]; then
                         for _ in {1..4}; do clearLine 1; done
                     fi
-                    printCenter "[ Status: $SUCCESS_STATUS Downloaded | $ERROR_STATUS Failed ]" "="
+                    printCenter "justify" "Status" ": $SUCCESS_STATUS Downloaded | $ERROR_STATUS Failed" "="
                 done
             fi
         fi
 
         for _ in {1..2}; do clearLine 1; done
-        printf "\n"
-        [[ $SUCCESS_STATUS -gt 0 ]] && printCenter "[ Downloaded: ""$SUCCESS_STATUS"" ]" "="
-        [[ $ERROR_STATUS -gt 0 ]] && printCenter "[ Failed: ""$ERROR_STATUS"" ]" "="
-        printf "\n"
+        newLine "\n"
+        [[ $SUCCESS_STATUS -gt 0 ]] && printCenter "justify" "Downloaded" ": ""$SUCCESS_STATUS""" "="
+        [[ $ERROR_STATUS -gt 0 ]] && printCenter "justify" "Failed" ": ""$ERROR_STATUS""" "="
+        newLine "\n"
 
         if [[ -z $SKIP_SUBDIRS ]]; then
             if [[ -n "${FOLDERS[*]}" ]]; then
@@ -317,7 +337,7 @@ downloadFolder() {
         fi
     else
         clearLine 1
-        printCenter "[ Failed, some unknown error ]" "="
+        printCenter "justify" "Failed" ", some unknown error" "="
     fi
 }
 
@@ -338,7 +358,7 @@ setupArguments() {
     API_URL="https://www.googleapis.com"
     API_VERSION="v3"
 
-    SHORTOPTS=":vVl:i:l:sp:d:ShUD-:"
+    SHORTOPTS=":vVl:iq:l:sp:d:ShuD-:"
     while getopts "${SHORTOPTS}" OPTION; do
         case "$OPTION" in
             # Parse longoptions # https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options/28466267#28466267
@@ -400,7 +420,7 @@ setupArguments() {
             h)
                 usage
                 ;;
-            U)
+            u)
                 update
                 ;;
             l)
@@ -466,29 +486,39 @@ setupArguments() {
 checkDebug() {
     if [[ -n $DEBUG ]]; then
         set -x
-        printCenter() {
-            printf "%s\n" "$1"
-        }
+        printCenter() { { [[ $# = 3 ]] && printf "%s\n" "$2"; } || { printf "%s%s\n" "$2" "$3"; }; }
+        clearLine() { :; } && newLine() { :; }
     else
         set +x
-        # This refreshes the interactive shell so we can use the $COLUMNS variable in the printCenter function.
-        shopt -s checkwinsize && (: && :)
-        trap 'shopt -s checkwinsize; (:;:)' SIGWINCH
+        if isTerminal; then
+            # This refreshes the interactive shell so we can use the $COLUMNS variable in the printCenter function.
+            shopt -s checkwinsize && (: && :)
+            if [[ $COLUMNS -lt 40 ]]; then
+                printCenter() { { [[ $# = 3 ]] && printf "%s\n" "[ $2 ]"; } || { printf "%s\n" "[ $2$3 ]"; }; }
+            else
+                trap 'shopt -s checkwinsize; (:;:)' SIGWINCH
+            fi
+        else
+            printCenter() { { [[ $# = 3 ]] && printf "%s\n" "[ $2 ]"; } || { printf "%s\n" "[ $2$3 ]"; }; }
+            clearLine() { :; }
+        fi
+        newLine() { printf "%b" "$1"; }
     fi
 }
 
 # If internet connection is not available.
 # Probably the fastest way, takes about 1 - 2 KB of data, don't check for more than 10 secs.
+# curl -m option is unreliable in some cases.
 # https://unix.stackexchange.com/a/18711 to timeout without any external program.
 checkInternet() {
-    printCenter "[ Checking Internet connection.. ]" "="
-    if [[ -t 1 ]]; then
+    printCenter "justify" "Checking Internet connection.." "-"
+    if isTerminal; then
         CHECK_INTERNET="$(sh -ic 'exec 3>&1 2>/dev/null; { curl --compressed -Is google.com 1>&3; kill 0; } | { sleep 10; kill 0; }' || :)"
     else
         CHECK_INTERNET="$(curl --compressed -Is google.com -m 10)"
     fi
     if [[ -z $CHECK_INTERNET ]]; then
-        clearLine 1 && printf "\n" && printCenter "[ Error: Internet connection not available ]" "=" && printf "\n"
+        clearLine 1 && newLine "\n" && printCenter "justify" "Error: Internet connection not available" "=" && newLine "\n"
         exit 1
     else
         clearLine 1
@@ -536,13 +566,13 @@ main() {
     setupTempfile
 
     START=$(printf "%(%s)T\\n" "-1")
-    printCenter "[ Starting script ]" "="
+    printCenter "justify" "Starting script" "-"
 
     processArguments
 
     END="$(printf "%(%s)T\\n" "-1")"
     DIFF="$((END - START))"
-    printCenter "[ Time Elapsed: ""$((DIFF / 60))"" minute(s) and ""$((DIFF % 60))"" seconds ]" "="
+    printCenter "normal" " Time Elapsed: ""$((DIFF / 60))"" minute(s) and ""$((DIFF % 60))"" seconds " "="
 }
 
 main "$@"
