Major Refactoring | Add parallel downloading | Custom flags
* Now uses drive api v3, increasing both functionality and speed.
* New flags: -d/--directory
             -p/--parallel
             -s | --skip-subdirs
	     -i | --input
             -l | --log
	     -v | --verbose
             -V | --verbose-progress
             -D | --debug
             -h | --help
             -U | --update

* Fix id extractiom from edu account links.
* All files can be downloaded present inside the folder.

* Fix install, update and format script

diff --git a/install_shfmt b/install_shfmt
--- a/install_shfmt
+++ b/install_shfmt
@@ -1,23 +1,24 @@
 #!/usr/bin/env bash
-CURRENT_SHELL="$(echo "$SHELL" | sed "s/\//\n/g" | tail -1)"
+CURRENT_SHELL="${SHELL##*/}"
 case "$CURRENT_SHELL" in
     'bash') SHELL_FILE="$(ls "$HOME"/.bashrc)" ;;
     'zsh') SHELL_FILE="$(ls "$HOME"/.zshrc)" ;;
+    *) echo "Not a supported shell" && exit 1 ;;
 esac
-PROFILE_FILE="$HOME"/.profile
 
-case "$(uname -a | sed 's/\s\+/\n/g' | tail -2 | sed -n 1p)" in
+case "$(uname -m)" in
     'armv7l') ARCH=arm ;;
     'i386') ARCH=386 ;;
     'x86_64') ARCH=amd64 ;;
+    *) echo "Not supported architecture" && exit 1 ;;
 esac
 
-if ! which shfmt > /dev/null; then
-    if [ ! -f "$HOME"/.shf/shfmt ]; then
+if ! type -p shfmt > /dev/null 2>&1; then
+    if [ ! -f "$HOME"/.shfmt/shfmt ]; then
         printf 'shfmt not installed\n'
         printf 'Fetching latest release...\n'
-        LATEST_RELEASE="$(curl https://github.com/mvdan/sh/releases.atom -s | sed -n 12p | cut -d ">" -f2 | cut -d "<" -f1)"
-        printf '\033[1A'
+        LATEST_RELEASE="$(ver="$(curl https://github.com/mvdan/sh/releases.atom -s | grep '<title>v.*</title>' -m1)" && regex="(>.*<)" && [[ $ver =~ $regex ]] && echo "${BASH_REMATCH[1]:1:-1}")"
+        printf "\033[1A\033[2K"
         printf "Latest Release: %s         \\n" "$LATEST_RELEASE"
         LINK=https://github.com/mvdan/sh/releases/download/"$LATEST_RELEASE"/shfmt_"$LATEST_RELEASE"_linux_"$ARCH"
         mkdir -p "$HOME"/.shfmt
@@ -26,19 +27,13 @@ if ! which shfmt > /dev/null; then
         chmod +x "$HOME"/.shfmt/shfmt
         PATH="$HOME/.shfmt/:$PATH"
         export PATH
-        if [ -n "$SHELL_FILE" ]; then
-            if [ -f "$SHELL_FILE" ]; then
-                echo "export PATH=$HOME/.shfmt/:$PATH" >> "$SHELL_FILE"
-            elif [ -f "$PROFILE_FILE" ]; then
-                echo "export PATH=$HOME/.shfmt/:$PATH" >> "$PROFILE_FILE"
-            fi
-        fi
+        echo "PATH=$HOME/.shfmt/:$PATH" >> "$SHELL_FILE"
         echo "shfmt installed"
         echo "shfmt --help"
     else
-        echo "Cannot install, not compatible shell file found"
+        echo "Cannot install, no compatible shell file found."
     fi
 else
     echo "shfmt already installed"
-    echo "Path: $(which shfmt)"
+    echo "Path: $(type -p shfmt)"
 fi
