Add flag to use aria2c as downloader
* -aria/--aria-flags

	Use aria2c to download. "-aria" doesn't take arguments.

        To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'

	aria can only resume downloads if either --key or --oatuh flag is used.

* Not using aria2c progress bar for now, will see it later. Kinda messes up output

* Change test.sh to test with aria and change workflow to install aria2

* change speed flag to use only K and M.

* remove .aria2 file if present

Fix https://github.com/Akianonymus/gdrive-downloader/issues/11

diff --git a/sh/release/gdl b/sh/release/gdl
--- a/sh/release/gdl
+++ b/sh/release/gdl
@@ -129,8 +129,10 @@ chmod u-w+r "$config_path_update_config"
 }
 _download_file(){
 [ $# -lt 3 ]&&printf "Missing arguments\n"&&return 1
-file_id_download_file="$1" name_download_file="$2" server_size_download_file="$3" parallel_download_file="$4"
-unset range_download_file status_download_file old_status_download_file left_download_file downloaded_download_file
+file_id_download_file="$1" name_download_file="$2" server_size_download_file="$3" parallel_download_file="$4" \
+use_aria_download_file="$DOWNLOAD_WITH_ARIA"
+unset range_download_file status_download_file old_status_download_file left_download_file downloaded_download_file \
+flag_download_file flag_value_download_file url_download_file cookies_download_file
 server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file")"
 _print_center "justify" "$name_download_file" " | ${server_size_download_file:+$server_size_readable_download_file}" "="
 if [ -s "$name_download_file" ];then
@@ -142,33 +144,42 @@ return 0
 else
 _print_center "justify" "File is partially" " present, resuming.." "-"
 range_download_file="Range: bytes=$local_size_download_file-$server_size_download_file"
+[ -z "${OAUTH_ENABLED:-$API_KEY_DOWNLOAD}" ]&&unset use_aria_download_file
 fi
 else
-range_download_file="Range: bytes=0-$server_size_download_file"
+[ "$server_size_download_file" -gt 0 ]&&range_download_file="Range: bytes=0-$server_size_download_file"
 _print_center "justify" "Downloading file.." "-"
 fi
 if [ -n "$OAUTH_ENABLED" ];then
 . "${TMPFILE}_ACCESS_TOKEN"
-curl -Ls $CURL_SPEED \
--H "$range_download_file" \
--H "Authorization: Bearer $ACCESS_TOKEN" \
-"$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true" >>"$name_download_file"&
-pid="$!"
+flag_download_file="--header" flag_value_download_file="Authorization: Bearer $ACCESS_TOKEN"
+url_download_file="$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true"
 elif [ -n "$API_KEY_DOWNLOAD" ];then
-curl -Ls $CURL_SPEED \
--H "$range_download_file" \
--e "https://drive.google.com" \
-"$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true&key=$API_KEY" >>"$name_download_file"&
-pid="$!"
+flag_download_file="--referer" flag_value_download_file="https://drive.google.com"
+url_download_file="$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true&key=$API_KEY"
 else
 "$EXTRA_LOG" "justify" "Fetching" " cookies.." "-"
-curl -c "$TMPFILE"COOKIE -I $CURL_PROGRESS -o /dev/null "https://drive.google.com/uc?export=download&id=$file_id_download_file"||:
+curl -c "${TMPFILE}_${file_id_download_file}_COOKIE" -I $CURL_PROGRESS -o /dev/null "https://drive.google.com/uc?export=download&id=$file_id_download_file"||:
 for _ in 1 2;do _clear_line 1;done
-confirm_string="$(_tmp="$(grep -F 'download_warning' "$TMPFILE"COOKIE)"&&printf "%s\n" "${_tmp##*$(printf '\t')}")"||:
-curl -L -s $CURL_SPEED \
--H "$range_download_file" \
--b "$TMPFILE"COOKIE \
-"https://drive.google.com/uc?export=download&id=$file_id_download_file${confirm_string:+&confirm=$confirm_string}" >>"$name_download_file"&
+confirm_string="$(_tmp="$(grep -F 'download_warning' "${TMPFILE}_${file_id_download_file}_COOKIE")"&&printf "%s\n" "${_tmp##*$(printf '\t')}")"||:
+flag_download_file="-b" flag_value_download_file="${TMPFILE}_${file_id_download_file}_COOKIE"
+[ -n "$use_aria_download_file" ]&&{
+cookies_download_file="$(sed -e "s/^\# .*//g" -e "s/^\#HttpOnly_//g" "${TMPFILE}_${file_id_download_file}_COOKIE")"
+printf "%s\n" "$cookies_download_file" >|"${TMPFILE}_${file_id_download_file}_COOKIE"
+flag_download_file="--load-cookies"
+}
+url_download_file="https://drive.google.com/uc?export=download&id=$file_id_download_file${confirm_string:+&confirm=$confirm_string}"
+fi
+if [ -n "$use_aria_download_file" ];then
+aria2c ${SPEED_LIMIT:+$ARIA_SPEED_LIMIT_FLAG} $SPEED_LIMIT $ARIA_EXTRA_FLAGS \
+"$flag_download_file" "$flag_value_download_file" \
+"$url_download_file" -o "$name_download_file"&
+pid="$!"
+else
+curl ${SPEED_LIMIT:+$CURL_SPEED_LIMIT_FLAG} $SPEED_LIMIT $CURL_EXTRA_FLAGS \
+--header "$range_download_file" \
+"$flag_download_file" "$flag_value_download_file" \
+"$url_download_file" >>"$name_download_file"&
 pid="$!"
 fi
 if [ -n "$parallel_download_file" ];then
@@ -190,6 +201,7 @@ fi
 if [ "$(wc -c <"$name_download_file")" -ge "$server_size_download_file" ];then
 for _ in 1 2;do _clear_line 1;done
 "${QUIET:-_print_center}" "justify" "Downloaded" "="&&_newline "\n"
+rm -f "$name.aria2"
 else
 "${QUIET:-_print_center}" "justify" "Error: Incomplete" " download." "=" 1>&2
 return 1
@@ -413,6 +425,11 @@ printf "%b" "
 The script can be used to download file/directory from google drive.\n
 Usage:\n ${0##*/} [options.. ] <file_[url|id]> or <folder[url|id]>\n
 Options:\n
+  -aria | --aria-flags 'flags' - Use aria2c to download. '-aria' does not take arguments.\n
+      To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'\n
+      Note 1: aria2c can only resume google drive downloads if '-k/--key' or '-o/--oauth' option is used, otherwise, it will use curl.\n
+      Note 2: aria split downloading won't work in normal mode ( without '-k' or '-o' flag ) because it cannot get the remote server size. Same for any other feature which uses remote server size.\n
+      Note 3: By above notes, conclusion is, aria is basically same as curl in normal mode, so it is recommended to be used only with '--key' and '--oauth' flag.\n
   -o | --oauth - Use this flag to trigger oauth authentication.\n
       Note: If both --oauth and --key flag is used, --oauth flag is preferred.\n
   -k | --key 'API KEY' ( optional arg ) - To download with api key. If api key is not specified, then the predefined api key will be used.\n
@@ -423,7 +440,7 @@ Options:\n
   -d | --directory 'foldername' - option to _download given input in custom directory.\n
   -s | --skip-subdirs - Skip downloading of sub folders present in case of folders.\n
   -p | --parallel 'no_of_files_to_parallely_upload' - Download multiple files in parallel.\n
-  --speed 'speed' - Limit the download speed, supported formats: 1K, 1M and 1G.\n
+  --speed 'speed' - Limit the download speed, supported formats: 1K, and 1M.\n
   -R | --retry 'num of retries' - Retry the file upload if it fails, postive integer as argument. Currently only for file uploads.\n
   -l | --log 'file_to_save_info' - Save downloaded files info to the given filename.\n
   -q | --quiet - Supress the normal output, only show success/error upload messages for files, and one extra line at the beginning for folder showing no. of files and sub folders.\n
@@ -476,9 +493,11 @@ exit 0
 _setup_arguments(){
 [ $# = 0 ]&&printf "Missing arguments\n"&&return 1
 unset LOG_FILE_ID OAUTH_ENABLED API_KEY_DOWNLOAD CONFIG FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD
-unset DEBUG QUIET VERBOSE VERBOSE_PROGRESS SKIP_INTERNET_CHECK RETRY
+unset DOWNLOAD_WITH_ARIA ARIA_EXTRA_FLAGS ARIA_SPEED_LIMIT_FLAG
+unset DEBUG QUIET VERBOSE VERBOSE_PROGRESS SKIP_INTERNET_CHECK RETRY SPEED_LIMIT
 unset ID_INPUT_ARRAY FINAL_INPUT_ARRAY
-CURL_PROGRESS="-s" EXTRA_LOG=":"
+CURL_PROGRESS="-s" CURL_SPEED_LIMIT_FLAG="--limit-rate" CURL_EXTRA_FLAGS="-Ls"
+EXTRA_LOG=":"
 CONFIG="$HOME/.gdl.conf"
 API_KEY="AIzaSyD2dHsZJ9b4OXuy5B_owiL8W18NaNOM8tk"
 API_URL="https://www.googleapis.com"
@@ -499,6 +518,12 @@ case "$1" in
 --info)_info;;
 -l|--log)_check_longoptions "$1" "$2"
 LOG_FILE_ID="$2"&&shift
+;;
+-aria|--aria-flags)DOWNLOAD_WITH_ARIA="true"
+[ "$1" = "--aria-flags" ]&&{
+_check_longoptions "$1" "$2"
+ARIA_EXTRA_FLAGS=" $ARIA_EXTRA_FLAGS $2 "&&shift
+}
 ;;
 -o|--oauth)OAUTH_ENABLED="true";;
 -k|--key)API_KEY_DOWNLOAD="true"
@@ -526,11 +551,11 @@ fi
 PARALLEL_DOWNLOAD="parallel"&&shift
 ;;
 --speed)_check_longoptions "$1" "$2"
-regex='^([0-9]+)([k,K]|[m,M]|[g,G])+$'
+regex='^([0-9]+)([k,K]|[m,M])+$'
 if printf "%s\n" "$2"|grep -qE "$regex";then
-CURL_SPEED="--limit-rate $2"&&shift
+SPEED_LIMIT="$2"&&shift
 else
-printf "Error: Wrong speed limit format, supported formats: 1K , 1M and 1G\n" 1>&2
+printf "Error: Wrong speed limit format, supported formats: 1K and 1M.\n" 1>&2
 exit 1
 fi
 ;;
@@ -560,6 +585,11 @@ shift
 done
 [ -z "$ID_INPUT_ARRAY" ]&&_short_help
 [ -n "$OAUTH_ENABLED" ]&&unset API_KEY_DOWNLOAD
+[ -n "$DOWNLOAD_WITH_ARIA" ]&&{
+command -v aria2c 1>|/dev/null||{ printf "%s\n" "Error: aria2c not installed."&&exit 1;}
+ARIA_SPEED_LIMIT_FLAG="--max-download-limit"
+ARIA_EXTRA_FLAGS="$ARIA_EXTRA_FLAGS -q --file-allocation=none --auto-file-renaming=false --continue"
+}
 _check_debug
 return 0
 }
@@ -669,9 +699,10 @@ fi
 return 0
 }
 _process_arguments(){
-export LOG_FILE_ID VERBOSE API_KEY API_URL API_VERSION \
+export DEBUG LOG_FILE_ID VERBOSE API_KEY API_URL API_VERSION \
 FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD SKIP_INTERNET_CHECK \
-COLUMNS CURL_SPEED TMPFILE CURL_PROGRESS EXTRA_LOG RETRY QUIET SOURCE_UTILS \
+COLUMNS TMPFILE CURL_PROGRESS EXTRA_LOG RETRY QUIET SPEED_LIMIT SOURCE_UTILS \
+DOWNLOAD_WITH_ARIA ARIA_EXTRA_FLAGS ARIA_SPEED_LIMIT_FLAG CURL_SPEED_LIMIT_FLAG CURL_EXTRA_FLAGS \
 OAUTH_ENABLED API_KEY_DOWNLOAD
 ${FOLDERNAME:+mkdir -p $FOLDERNAME}
 cd "${FOLDERNAME:-.}" 2>|/dev/null 1>&2||exit 1
