Add support for downloading documents | Resolve https://github.com/Akianonymus/gdrive-downloader/issues/34
Also add a -df / --document-format flag to download in specific format

diff --git a/release/sh/gdl b/release/sh/gdl
--- a/release/sh/gdl
+++ b/release/sh/gdl
@@ -504,7 +504,7 @@ _json_value(){
 { [ "$2" -gt 0 ] 2>|/dev/null&&no_of_lines_json_value="$2";}||:
 { [ "$3" -gt 0 ] 2>|/dev/null&&num_json_value="$3";}||{ ! [ "$3" = all ]&&num_json_value=1;}
 _tmp="$(grep -o "\"$1\"\:.*" ${no_of_lines_json_value:+-m} $no_of_lines_json_value)"||return 1
-printf "%s\n" "$_tmp"|sed -e 's/.*"'"$1""\"://" -e 's/[",]*$//' -e 's/["]*$//' -e 's/[,]*$//' -e "s/^ //" -e 's/^"//' -n -e "$num_json_value"p||:
+printf "%s\n" "$_tmp"|sed -e 's|.*"'"$1""\":||" -e 's/[",]*$//' -e 's/["]*$//' -e 's/[,]*$//' -e "s/^ //" -e 's/^"//' -n -e "$num_json_value"p||:
 return 0
 }
 _move_cursor(){
@@ -635,19 +635,24 @@ return 1
 }
 _clear_line 1
 case "$mime_check_id" in
-*folder*)\
+"application/vnd.google-apps.folder")\
 FOLDER_ID="$id_check_id"
 _print_center "justify" "Folder Detected" "="
+;;
+"application/vnd.google-apps.document")\
+FILE_ID="$id_check_id" \
+FILE_MIME_TYPE="$mime_check_id"
+_print_center "justify" "Document Detected" "="
 ;;
 *)\
 SIZE="$(printf "%s\n" "$json_check_id"|_json_value size 1 1)"||{
 printf "\n"&&__error_check_id "Cannot fetch size of file."&&return 1
 }
-FILE_ID="$id_check_id"
+FILE_ID="$id_check_id" FILE_MIME_TYPE="$mime_check_id"
 _print_center "justify" "File Detected" "="
 esac
 _newline "\n"
-export NAME SIZE FILE_ID FOLDER_ID
+export NAME SIZE FILE_ID FILE_MIME_TYPE FOLDER_ID
 return 0
 }
 _extract_id(){
@@ -671,43 +676,74 @@ _api_request_oauth \
 _check_id \
 _extract_id
 } 2>|/dev/null 1>&2||:
+_cookies_and_document_stuff(){
+"$EXTRA_LOG" "justify" "Fetching" " ${1:?}.." "-"
+_curl --compressed $CURL_PROGRESS ${3:-} \
+"${4:---header}" "${5:-}" \
+-c "${TMPFILE}_${file_id_download_file}_COOKIE" -o "${TMPFILE}_${file_id_download_file}_misc" \
+"${2:?}"||return 1
+for _ in 1 2;do _clear_line 1;done
+}
 _common_stuff(){
-export OAUTH_ENABLED TMPFILE ACCESS_TOKEN API_URL API_VERSION API_KEY API_KEY_DOWNLOAD EXTRA_LOG CURL_PROGRESS DOWNLOADER
+export OAUTH_ENABLED TMPFILE ACCESS_TOKEN API_URL API_VERSION API_KEY API_KEY_DOWNLOAD EXTRA_LOG CURL_PROGRESS DOWNLOADER DOCUMENT_FORMAT DOCUMENT_FORMAT_ESCAPED
+if [ -n "${OAUTH_ENABLED:-$API_KEY_DOWNLOAD}" ];then
+url_download_file="$API_URL/drive/$API_VERSION/files/$file_id_download_file$(case "$mime_download_file" in
+"application/vnd.google-apps.document")printf "%s" "/export?mimeType=$DOCUMENT_FORMAT_ESCAPED";;
+*)printf "?alt=media"
+esac)&supportsAllDrives=true&includeItemsFromAllDrives=true"
 if [ -n "$OAUTH_ENABLED" ];then
 . "${TMPFILE}_ACCESS_TOKEN"
 flag_download_file="--header" flag_value_download_file="Authorization: Bearer $ACCESS_TOKEN"
-url_download_file="$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true"
 elif [ -n "$API_KEY_DOWNLOAD" ];then
 flag_download_file="--referer" flag_value_download_file="https://drive.google.com"
-url_download_file="$API_URL/drive/$API_VERSION/files/$file_id_download_file?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true&key=$API_KEY"
+url_download_file="$url_download_file&key=$API_KEY"
+fi
+case "$mime_download_file" in
+"application/vnd.google-apps.document")_cookies_and_document_stuff "document size" "$url_download_file" "-LI" "$flag_download_file" "$flag_value_download_file"||return 1
+server_size_download_file="$(($(_tmp="$(grep -F 'content-length' "${TMPFILE}_${file_id_download_file}_misc")"&&_tmp="${_tmp##content-length: }"&&printf "%s\n" "${_tmp%"$(printf '\r')"}")))"
+server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file" 2>|/dev/null)"
+_clear_line 1
+_print_center "justify" "$name_download_file" " | $server_size_readable_download_file" "="
+;;
+*):
+esac
 else
-"$EXTRA_LOG" "justify" "Fetching" " cookies.." "-"
-_curl $CURL_PROGRESS \
--c "${TMPFILE}_${file_id_download_file}_COOKIE" -o "${TMPFILE}_${file_id_download_file}_confirm_string" \
-"https://drive.google.com/uc?export=download&id=$file_id_download_file"||:
-for _ in 1 2;do _clear_line 1;done
+flag_download_file="-b" flag_value_download_file="${TMPFILE}_${file_id_download_file}_COOKIE"
+case "$mime_download_file" in
+"application/vnd.google-apps.document")\
+json_common_stuff="$("$API_REQUEST_FUNCTION" "files/$file_id_download_file?alt=json&fields=exportLinks")"||return 1
+url_download_file="$(printf "%s\n" "$json_common_stuff"|_json_value "$DOCUMENT_FORMAT" 1 1)"||return 0
+_cookies_and_document_stuff "cookies and document size" "$url_download_file" "-LI"||return 1
+server_size_download_file="$(($(_tmp="$(grep -F 'content-length' "${TMPFILE}_${file_id_download_file}_misc")"&&_tmp="${_tmp##content-length: }"&&printf "%s\n" "${_tmp%"$(printf '\r')"}")))"
+server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file" 2>|/dev/null)"
+_clear_line 1
+_print_center "justify" "$name_download_file" " | $server_size_readable_download_file" "="
+;;
+*)\
+url_download_file="https://drive.google.com/uc?export=download&id=$file_id_download_file"
+_cookies_and_document_stuff "cookies" "$url_download_file" "-L"||return 1
 confirm_string="$(_tmp="$(grep -F 'download_warning' "${TMPFILE}_${file_id_download_file}_COOKIE")"&&printf "%s\n" "${_tmp##*"$(printf '\t')"}")"||:
 [ -z "$confirm_string" ]&&{
-confirm_string="$(_tmp="$(grep -Eo "export=download.*$file_id_download_file.*confirm=\w+" "${TMPFILE}_${file_id_download_file}_confirm_string")"&&printf "%s\n" "${_tmp##*=}")"
+confirm_string="$(_tmp="$(grep -Eo "export=download.*$file_id_download_file.*confirm=\w+" "${TMPFILE}_${file_id_download_file}_misc")"&&printf "%s\n" "${_tmp##*=}")"
 }
-flag_download_file="-b" flag_value_download_file="${TMPFILE}_${file_id_download_file}_COOKIE"
+url_download_file="$url_download_file${confirm_string:+&confirm=$confirm_string}"
+esac
 [ "$DOWNLOADER" = "aria2c" ]&&{
 cookies_download_file="$(sed -e "s/^\# .*//g" -e "s/^\#HttpOnly_//g" "${TMPFILE}_${file_id_download_file}_COOKIE")"
 printf "%s\n" "$cookies_download_file" >|"${TMPFILE}_${file_id_download_file}_COOKIE"
 flag_download_file="--load-cookies"
 }
-url_download_file="https://drive.google.com/uc?export=download&id=$file_id_download_file${confirm_string:+&confirm=$confirm_string}"
 fi
 return 0
 }
 _download_with_aria2c(){
 export ARIA_FLAGS QUIET
 [ $# -lt 3 ]&&printf "Missing arguments\n"&&return 1
-file_id_download_file="$1" name_download_file="$2" server_size_download_file="$3" parallel_download_file="$4"
+file_id_download_file="$1" name_download_file="$2" mime_download_file="$3" server_size_download_file="$4" parallel_download_file="$5"
 unset flag_download_file flag_value_download_file url_download_file cookies_download_file
-server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file")"
-_print_center "justify" "$name_download_file" " | ${server_size_download_file:+$server_size_readable_download_file}" "="
-_common_stuff
+server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file" 2>|/dev/null)"
+_print_center "justify" "$name_download_file" " | $server_size_readable_download_file" "="
+_common_stuff||return 1
 download_status=0
 aria2c $ARIA_FLAGS \
 "$flag_download_file" "$flag_value_download_file" \
@@ -725,26 +761,34 @@ return 0
 _download_with_curl(){
 export QUIET
 [ $# -lt 3 ]&&printf "Missing arguments\n"&&return 1
-file_id_download_file="$1" name_download_file="$2" server_size_download_file="$3" parallel_download_file="$4"
+file_id_download_file="$1" name_download_file="$2" mime_download_file="$3" server_size_download_file="$4" parallel_download_file="$5"
 unset range_download_file downloaded_download_file old_downloaded_download_file left_download_file speed_download_file eta_download_file \
 flag_download_file flag_value_download_file url_download_file cookies_download_file
-server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file")"
-_print_center "justify" "$name_download_file" " | ${server_size_download_file:+$server_size_readable_download_file}" "="
+server_size_readable_download_file="$(_bytes_to_human "$server_size_download_file" 2>|/dev/null)"
+_print_center "justify" "$name_download_file" " | $server_size_readable_download_file" "="
+__check_for_resume_download_with_curl(){
 if [ -s "$name_download_file" ];then
 local_size_download_file="$(_actual_size_in_bytes "$name_download_file")"
-if [ "$local_size_download_file" -ge "$server_size_download_file" ];then
+if [ "$local_size_download_file" -ge "$((server_size_download_file))" ];then
 "${QUIET:-_print_center}" "justify" "File already present" "="&&_newline "\n"
 _log_in_file
-return 0
+return 1
 else
 _print_center "justify" "File is partially" " present, resuming.." "-"
 range_download_file="Range: bytes=$local_size_download_file-$server_size_download_file"
 fi
 else
-[ "$server_size_download_file" -gt 0 ]&&range_download_file="Range: bytes=0-$server_size_download_file"
+[ "$((server_size_download_file))" -gt 0 ]&&range_download_file="Range: bytes=0-$server_size_download_file"
 _print_center "justify" "Downloading file.." "-"
 fi
-_common_stuff
+}
+case "$mime_download_file" in
+"application/vnd.google-apps.document")_common_stuff||return 1
+__check_for_resume_download_with_curl||return 0
+;;
+*)__check_for_resume_download_with_curl||return 0
+_common_stuff||return 1
+esac
 _curl -Ls \
 --header "$range_download_file" \
 "$flag_download_file" "$flag_value_download_file" \
@@ -767,7 +811,7 @@ _print_center "justify" "Speed: $(_bytes_to_human "$speed_download_file")/s " "|
 old_downloaded_download_file="$downloaded_download_file"
 done
 fi
-if [ "$(_actual_size_in_bytes "$name_download_file")" -ge "$server_size_download_file" ];then
+if [ "$(_actual_size_in_bytes "$name_download_file")" -ge "$((server_size_download_file))" ];then
 for _ in 1 2 3;do _clear_line 1;done
 "${QUIET:-_print_center}" "justify" "Downloaded" "="&&_newline "\n"
 rm -f -- "$name.aria2"
@@ -779,27 +823,32 @@ _log_in_file "$name_download_file" "$server_size_readable_download_file" "$file_
 return 0
 }
 _download_file_main(){
-export DOWNLOADER
+export DOWNLOADER DOCUMENT_FORMAT_NAME
 [ $# -lt 2 ]&&printf "Missing arguments\n"&&return 1
-unset line_download_file_main fileid_download_file_main name_download_file_main size_download_file_main parallel_download_file_main RETURN_STATUS sleep_download_file_main&&retry_download_file_main="${RETRY:-0}"
+unset line_download_file_main fileid_download_file_main name_download_file_main mime_download_file_main size_download_file_main parallel_download_file_main RETURN_STATUS sleep_download_file_main&&retry_download_file_main="${RETRY:-0}"
 if [ "$1" = parse ];then
+line_download_file_main="${2:?}"
 parallel_download_file_main="$3"
-line_download_file_main="$2"
 fileid_download_file_main="${line_download_file_main%%"|:_//_:|"*}"
-name_download_file_main="${line_download_file_main##*"|:_//_:|"}"
-size_download_file_main="$(_tmp="${line_download_file_main#*"|:_//_:|"}"&&printf "%s\n" "${_tmp%"|:_//_:|"*}")"
+name_download_file_main="${line_download_file_main##"$fileid_download_file_main""|:_//_:|"}" name_download_file_main="${name_download_file_main%%"|:_//_:|"*}"
+mime_download_file_main="${line_download_file_main##*"|:_//_:|"}"
+size_download_file_main="${line_download_file_main##*"$name_download_file_main""|:_//_:|"}" size_download_file_main="${size_download_file_main%%"|:_//_:|"*}"
 else
-fileid_download_file_main="$2"
-name_download_file_main="$3"
-size_download_file_main="$4"
-parallel_download_file_main="$5"
+fileid_download_file_main="${2:?}"
+name_download_file_main="${3:?}"
+mime_download_file_main="$4"
+size_download_file_main="$5" size_download_file_main="$((size_download_file_main))"
 fi
 [ -z "${fileid_download_file_main:+$name_download_file_main}" ]&&return 0
+case "$mime_download_file_main" in
+"application/vnd.google-apps.document")name_download_file_main="$name_download_file_main.$DOCUMENT_FORMAT_NAME";;
+*):
+esac
 unset RETURN_STATUS&&until [ "$retry_download_file_main" -le 0 ]&&[ -n "$RETURN_STATUS" ];do
 if [ -n "$parallel_download_file_main" ];then
-"_download_with_$DOWNLOADER" "$fileid_download_file_main" "$name_download_file_main" "$size_download_file_main" true 2>|/dev/null 1>&2&&RETURN_STATUS=1&&break
+"_download_with_$DOWNLOADER" "$fileid_download_file_main" "$name_download_file_main" "$mime_download_file_main" "$size_download_file_main" true 2>|/dev/null 1>&2&&RETURN_STATUS=1&&break
 else
-"_download_with_$DOWNLOADER" "$fileid_download_file_main" "$name_download_file_main" "$size_download_file_main"&&RETURN_STATUS=1&&break
+"_download_with_$DOWNLOADER" "$fileid_download_file_main" "$name_download_file_main" "$mime_download_file_main" "$size_download_file_main"&&RETURN_STATUS=1&&break
 fi
 sleep "$((sleep_download_file_main+=1))"
 RETURN_STATUS=2 retry_download_file_main="$((retry_download_file_main-1))"&&continue
@@ -832,9 +881,11 @@ else
 _search_error_message_download_folder "$json_search_download_folder"
 fi&&_clear_line 1
 "$EXTRA_LOG" "justify" "Preparing files list.." "="
-files_download_folder="$(printf "%s\n" "$json_search_download_folder"|grep '"size":' -B3|_json_value id all all)"||:
-files_size_download_folder="$(printf "%s\n" "$json_search_download_folder"|_json_value size all all)"||:
-files_name_download_folder="$(printf "%s\n" "$json_search_download_folder"|grep size -B2|_json_value name all all)"||:
+info_files_download_folder="$(printf "%s\n" "$json_search_download_folder"|grep '"size":' -B3)"
+files_download_folder="$(printf "%s\n" "$info_files_download_folder"|_json_value id all all)"||:
+files_size_download_folder="$(printf "%s\n" "$info_files_download_folder"|_json_value size all all)"||:
+files_name_download_folder="$(printf "%s\n" "$info_files_download_folder"|_json_value name all all)"||:
+files_mime_download_folder="$(printf "%s\n" "$info_files_download_folder"|_json_value mimeType all all)"||:
 exec 5<<EOF
 $(printf "%s\n" "$files_download_folder")
 EOF
@@ -844,10 +895,13 @@ EOF
 exec 7<<EOF
 $(printf "%s\n" "$files_name_download_folder")
 EOF
-files_list_download_folder="$(while IFS= read -r id <&5&&read -r size <&6&&read -r name <&7;do
-[ -n "${id:+$name}" ]&&printf "%s\n" "$id|:_//_:|$size|:_//_:|$name"
+exec 8<<EOF
+$(printf "%s\n" "$files_mime_download_folder")
+EOF
+files_list_download_folder="$(while IFS= read -r id <&5&&read -r size <&6&&read -r name <&7&&read -r mime <&8;do
+[ -n "${id:+$name}" ]&&printf "%s\n" "$id|:_//_:|$name|:_//_:|$((size))|:_//_:|$mime"
 done)"
-exec 5<&-&&exec 6<&-&&exec 7<&-
+exec 5<&-&&exec 6<&-&&exec 7<&-&&exec 8<&-
 _clear_line 1
 [ -n "$INCLUDE_FILES" ]&&files_list_download_folder="$(printf "%s\n" "$files_list_download_folder"|grep -E "$INCLUDE_FILES")"
 [ -n "$EXCLUDE_FILES" ]&&files_list_download_folder="$(printf "%s\n" "$files_list_download_folder"|grep -Ev "$EXCLUDE_FILES")"
@@ -1234,6 +1288,30 @@ EOF
 _parser_setup_flag_process 4<<'EOF'
 export FOLDERNAME="${2}" && _parser_shift 
 EOF
+_parser_setup_flag "-df --document-format" 1 required "document type"
+_parser_setup_flag_help \
+"Can be used for documents to be downloaded in different format, default is docx.
+
+Available formats are: rtf, odt, html, pdf, epub, zip, docx, txt"
+_parser_setup_flag_preprocess 4<<'EOF'
+DOCUMENT_FORMAT_NAME="docx"
+DOCUMENT_FORMAT="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
+DOCUMENT_FORMAT_ESCAPED="application%2Fvnd.openxmlformats-officedocument.wordprocessingml.document"
+EOF
+_parser_setup_flag_process 4<<'EOF'
+case "${2}" in 
+    rtf) DOCUMENT_FORMAT="application/rtf" DOCUMENT_FORMAT_ESCAPED="application%2Frtf" ;;
+    odt) DOCUMENT_FORMAT="application/vnd.oasis.opendocument.text" DOCUMENT_FORMAT_ESCAPED="application%2Fvnd.oasis.opendocument.text" ;;
+    html) DOCUMENT_FORMAT="text/html" DOCUMENT_FORMAT_ESCAPED="text%2Fhtml" ;;
+    pdf) DOCUMENT_FORMAT="application/pdf" DOCUMENT_FORMAT_ESCAPED="application%2Fpdf" ;;
+    epub) DOCUMENT_FORMAT="application/epub+zip" DOCUMENT_FORMAT_ESCAPED="application%2Fepub%2Bzip" ;;
+    zip) DOCUMENT_FORMAT="application/zip" DOCUMENT_FORMAT_ESCAPED="application%2Fzip" ;;
+    docx) DOCUMENT_FORMAT="application/vnd.openxmlformats-officedocument.wordprocessingml.document" DOCUMENT_FORMAT_ESCAPED="application%2Fvnd.openxmlformats-officedocument.wordprocessingml.document" ;;
+    txt) DOCUMENT_FORMAT="text/plain" DOCUMENT_FORMAT_ESCAPED="text%2Fplain" ;;
+    *) printf "\nError: Wrong document format.\nAvailable formats are: rtf, odt, pdf, epub, zip, docx, txt" && return 1 ;;
+esac
+export DOCUMENT_FORMAT_NAME="${2}" DOCUMENT_FORMAT DOCUMENT_FORMAT_ESCAPED && _parser_shift 
+EOF
 _parser_setup_flag "-s --skip-subdirs" 0
 _parser_setup_flag_help \
 "Skip downloading of sub folders present in case of folders."
@@ -1541,7 +1619,7 @@ trap '' TSTP
 export MAIN_PID="$$"
 }
 _process_arguments(){
-export FOLDERNAME TOTAL_INPUTS FILE_ID="" FOLDER_ID="" NAME="" PARALLEL_DOWNLOAD SIZE=""
+export FOLDERNAME TOTAL_INPUTS FILE_ID="" FOLDER_ID="" NAME="" FILE_MIME_TYPE="" PARALLEL_DOWNLOAD SIZE=""
 [ -n "$FOLDERNAME" ]&&mkdir -p -- "$FOLDERNAME"
 cd -- "${FOLDERNAME:-.}" 2>|/dev/null 1>&2||exit 1
 _SEEN="" index_process_arguments=0
@@ -1556,7 +1634,7 @@ _check_id "$FILE_ID"||continue
 if [ -n "$FOLDER_ID" ];then
 _download_folder "$FOLDER_ID" "$NAME" "${PARALLEL_DOWNLOAD:-}"
 else
-_download_file_main noparse "$FILE_ID" "$NAME" "$SIZE"
+_download_file_main noparse "$FILE_ID" "$NAME" "$FILE_MIME_TYPE" "$SIZE"
 fi
 done
 return 0
