Add shellcheck linting | merge.sh => release.sh | format.sh => format_and_lint.sh
* seperate download test in CI

* some improvements to release script

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,16 +31,18 @@ jobs:
               gdl --info
           sh install.sh -U  && sh install.sh -c custom_gdl
               custom_gdl --info
-    - name: 'Format, Merge and Download test'
+    - name: 'Format, lint ( shellcheck ) and release test'
       run: |
           set -e
-          { { command -v apt-get && apt-get install aria2 snapd -yqq && snap install shfmt ;} ||
-            { command -v brew && brew install shfmt aria2;} ;} 2>| /dev/null 1>&2
+          { { command -v apt-get && apt-get install aria2 snapd shellcheck -yqq && snap install shfmt ;} ||
+            { command -v brew && brew install shfmt aria2 shellcheck;} ;} 2>| /dev/null 1>&2
 
           # merge test
-          sh merge.sh
-          { [ -n "$(git diff)" ] && printf "%s\n" "Error: Run merge.sh before pushing the commits" && git diff && exit 1 ;} || :
-
+          sh release.sh
+          { [ -n "$(git diff)" ] && printf "%s\n" "Error: Run release.sh before pushing the commits" && git diff && exit 1 ;} || :
+    - name: 'Download test'
+      run: |
+          set -e
           # update bash for macos
           command -v brew && brew reinstall bash
           # download tests
