Refactor how help contents are shown | Add support to print indiviual flag help
create a new file called utils.sh where functions will be stored which
can be used by both posix and bash scripts without any performance
regression

diff --git a/bash/release/gdl b/bash/release/gdl
--- a/bash/release/gdl
+++ b/bash/release/gdl
@@ -1,5 +1,111 @@
 #!/usr/bin/env bash
 SELF_SOURCE="true"
+_create_help(){
+_set_help "-aria --aria-flags" \
+'flags' \
+"use aria2c to download. '-aria' does not take arguments." \
+"To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'
+
+Note 1: aria2c can only resume google drive downloads if '-k/--key' or '-o/--oauth' option is used.
+
+Note 2: aria split downloading won't work in normal mode ( without '-k' or '-o' flag ) because it cannot get the remote server size. Same for any other feature which uses remote server size.
+
+Note 3: By above notes, conclusion is, aria is basically same as curl in normal mode, so it is recommended to be used only with '--key' and '--oauth' flag."
+_set_help "-o --oauth" \
+"" \
+"Use this flag to trigger oauth authentication." \
+"Note: If both --oauth and --key flag is used, --oauth flag is preferred."
+_set_help "-a --account" \
+"account name" \
+"Use different account than the default one." \
+"To change the default account name, use this format, -a/--account default=account_name"
+_set_help "-la --list-accounts" \
+"" \
+"Print all configured accounts in the config files."
+_set_help "-ca --create-account" \
+"account name" \
+"To create a new account with the given name if does not already exists."
+_set_help "-da --delete-account" \
+"account name" \
+"To delete an account information from config file."
+_set_help "-k --key" \
+"API KEY( optional )" \
+"To download with api key. If api key is not specified, then the predefined api key will be used." \
+"To save your api key in config file, use 'gdl --key default=your api key'.
+
+     API key will be saved in '/data/data/com.termux/files/home/.gdl.conf' and will be used from now on.
+
+     Note: If both --key and --key oauth is used, --oauth flag is preferred."
+_set_help "-c --config" \
+"config file path" \
+"Override default config file with custom config file. Default: /data/data/com.termux/files/home/.gdl.conf"
+_set_help "-d --directory" \
+"foldername" \
+"To download given input in custom directory."
+_set_help "-s --skip-subdirs" \
+"" \
+"Skip downloading of sub folders present in case of folders."
+_set_help "-p --parallel" \
+"no of files to parallely download" \
+"Download multiple files in parallel."
+_set_help "--proxy" \
+"http://user:password@host:port" \
+"Specify a proxy to use, should be in the format accepted by curl --proxy and aria2c --all-proxy flag."
+_set_help "--speed" \
+"speed" \
+"Limit the download speed, supported formats: 1K and 1M."
+_set_help "-ua --user-agent" \
+"user agent string" \
+"Specify custom user agent."
+_set_help "-R --retry" \
+"num of retries" \
+"Retry the file upload if it fails, postive integer as argument. Currently only for file uploads."
+_set_help "-in --include" \
+"pattern" \
+"Only download the files which contain the given pattern - Applicable for folder downloads." \
+"e.g: gdl local_folder --include '1', will only include with files with pattern '1' in the name. Regex can be used which works with grep -E command."
+_set_help "-ex --exclude" \
+"pattern" \
+"Only download the files which does not contain the given pattern - Applicable for folder downloads." \
+"e.g: gdl local_folder --exclude '1', will only include with files with pattern '1' not present in the name. Regex can be used which works with grep -E command."
+_set_help "-l --log" \
+"file to save info" \
+"Save downloaded files info to the given filename."
+_set_help "-q --quiet" \
+"" \
+"Supress the normal output, only show success/error upload messages for files, and one extra line at the beginning for folder showing no. of files and sub folders."
+_set_help "--verbose" \
+"" \
+"Display detailed message (only for non-parallel uploads)"
+_set_help "--skip-internet-check" \
+"" \
+"Do not check for internet connection, recommended to use in sync jobs."
+_set_help "-V --version --info" \
+"" \
+"Show detailed info, only if script is installed system wide."
+_set_help "-D --debug" \
+"" \
+"Display script command trace."
+_set_help "-h --help" \
+"flag name (optional)" \
+"Print help for all flags and basic usage instructions." \
+"To see help for a specific flag, --help flag_name ( with or without dashes )
+e.g: ${0##*/} --help aria"
+[ "$GDL_INSTALLED_WITH" = script ]&&{
+_set_help "-u --update" \
+"" \
+"Update the installed script in your system."
+_set_help "--uninstall" \
+"" \
+"Uninstall script, remove related files."
+}
+ALL_HELP="
+The script can be used to download file/directory from google drive.
+
+Usage: ${0##*/} [options.. ] <file_[url|id]> or <folder[url|id]>
+
+Options:$ALL_HELP"
+}
 _account_name_valid(){
 declare name="${1:-}" account_name_regex='^([A-Za-z0-9_])+$'
 [[ $name =~ $account_name_regex ]]||return 1
@@ -780,47 +886,45 @@ _api_request_oauth \
 _check_id \
 _extract_id
 _usage(){
-printf "%b" "
-The script can be used to download file/directory from google drive.\n
-Usage:\n ${0##*/} [options.. ] <file_[url|id]> or <folder[url|id]>\n
-Options:\n
-  -aria | --aria-flags 'flags' - Use aria2c to download. '-aria' does not take arguments.\n
-      To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'\n
-      Note 1: aria2c can only resume google drive downloads if '-k/--key' or '-o/--oauth' option is used.\n
-      Note 2: aria split downloading won't work in normal mode ( without '-k' or '-o' flag ) because it cannot get the remote server size. Same for any other feature which uses remote server size.\n
-      Note 3: By above notes, conclusion is, aria is basically same as curl in normal mode, so it is recommended to be used only with '--key' and '--oauth' flag.\n
-  -o | --oauth - Use this flag to trigger oauth authentication.\n
-      Note: If both --oauth and --key flag is used, --oauth flag is preferred.\n
-  -a | --account 'account name' - Use different account than the default one.\n
-      To change the default account name, use this format, -a/--account default=account_name\n
-  -la | --list-accounts - Print all configured accounts in the config files.\n
-  -ca | --create-account 'account name' - To create a new account with the given name if does not already exists.\n
-  -da | --delete-account 'account name' - To delete an account information from config file. \n
-  -k | --key 'API KEY' ( optional arg ) - To download with api key. If api key is not specified, then the predefined api key will be used.\n
-      To save your api key in config file, use 'gdl --key default=your api key'.\n
-      API key will be saved in '$HOME/.gdl.conf' and will be used from now on.\n
-      Note: If both --key and --key oauth is used, --oauth flag is preferred.\n
-  -c | --config 'config file path' - Override default config file with custom config file. Default: $HOME/.gdl.conf\n
-  -d | --directory 'foldername' - option to _download given input in custom directory.\n
-  -s | --skip-subdirs - Skip downloading of sub folders present in case of folders.\n
-  -p | --parallel 'no_of_files_to_parallely_upload' - Download multiple files in parallel.\n
-  --proxy 'http://user:password@host:port' - Specify a proxy to use, should be in the format accepted by curl --proxy and aria2c --all-proxy flag.\n
-  --speed 'speed' - Limit the download speed, supported formats: 1K and 1M.\n
-  -ua | --user-agent 'user agent string' - Specify custom user agent.\n
-  -R | --retry 'num of retries' - Retry the file upload if it fails, postive integer as argument. Currently only for file uploads.\n
-  -in | --include 'pattern' - Only download the files which contain the given pattern - Applicable for folder downloads.\n
-      e.g: ${0##*/} local_folder --include '1', will only include with files with pattern '1' in the name. Regex can be used which works with grep -E command.\n
-  -ex | --exclude 'pattern' - Only download the files which does not contain the given pattern - Applicable for folder downloads.\n
-      e.g: ${0##*/} local_folder --exclude '1', will only include with files with pattern '1' not present in the name. Regex can be used which works with grep -E command.\n
-  -l | --log 'file_to_save_info' - Save downloaded files info to the given filename.\n
-  -q | --quiet - Supress the normal output, only show success/error upload messages for files, and one extra line at the beginning for folder showing no. of files and sub folders.\n
-  -V | --verbose - Display detailed message (only for non-parallel uploads).\n
-  --skip-internet-check - Do not check for internet connection, recommended to use in sync jobs.\n
-  $([[ $GDL_INSTALLED_WITH == script ]]&&printf '%s\n' '-u | --update - Update the installed script in your system.\n
-  -U | --uninstall - Uninstall script, remove related files.\n
-  -V | --version | --info - Show detailed info, only if script is installed system wide.\n')
-  -D | --debug - Display script command trace.\n
-  -h | --help - Display usage instructions.\n"
+DEBUG="" _check_debug
+_HELP_BAR="$(_print_center "normal" "_" "_")"
+[[ -n $_HELP_BAR ]]&&export _HELP_BAR="$_HELP_BAR
+"
+_set_help(){
+declare content1="$3" content2 all_content
+[[ -n $4 ]]&&{
+content2="
+"
+while read -r line <&4;do
+content2="$content2
+        $line"
+done 4<<EOF
+$4
+EOF
+}
+start="${1// / | }"
+start="    $start ${2:+\"$2\"} => "
+all_content="$start$content1$content2"
+for f in $1;do
+declare flag="${f//-/}"
+_set_value d "help_$flag" "$all_content"
+done
+ALL_HELP="$ALL_HELP
+$_HELP_BAR
+$all_content"
+}
+_create_help
+[[ -n $1 ]]&&{
+declare tmp_help
+_set_value i tmp_help "help_${1//-/}"
+if [[ -z $tmp_help ]];then
+printf "%s\n" "Error: No help found for $1"
+else
+printf "%s\n%s\n%s\n" "$_HELP_BAR" "$tmp_help" "$_HELP_BAR"
+fi
+exit 0
+}
+printf "%s\n" "$ALL_HELP"
 exit 0
 }
 _short_help(){
@@ -852,7 +956,7 @@ return 0
 _setup_arguments(){
 [[ $# == 0 ]]&&printf "%s: Missing arguments\n" "${FUNCNAME[0]}"&&return 1
 unset LIST_ACCOUNTS UPDATE_DEFAULT_ACCOUNT CUSTOM_ACCOUNT_NAME NEW_ACCOUNT_NAME DELETE_ACCOUNT_NAME ACCOUNT_ONLY_RUN
-unset LOG_FILE_ID OAUTH_ENABLED API_KEY_DOWNLOAD FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD
+unset LOG_FILE_ID OAUTH_ENABLED API_KEY_DOWNLOAD FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD ALL_HELP
 unset DEBUG QUIET VERBOSE SKIP_INTERNET_CHECK RETRY SPEED_LIMIT USER_AGENT PROXY
 unset ID_INPUT_ARRAY FINAL_INPUT_ARRAY INCLUDE_FILES EXCLUDE_FILES
 unset ARIA_FLAGS CURL_FLAGS
@@ -872,12 +976,17 @@ SCOPE="$API_URL/auth/drive" \
 REDIRECT_URI="urn:ietf:wg:oauth:2.0:oob" \
 TOKEN_URL="https://accounts.google.com/o/oauth2/token"
 _check_longoptions(){
-[[ -z $2 ]]&&printf '%s: %s: option requires an argument\nTry '"%s -h/--help"' for more information.\n' "${0##*/}" "$1" "${0##*/}"&&exit 1
+[[ -z $2 ]]&&{
+printf "%s\n" "${0##*/}: $1: flag requires an argument."
+printf "\n%s\n" "Help:"
+printf "%s\n" "    $(_usage "$1")"
+exit 1
+}
 return 0
 }
 while [[ $# -gt 0 ]];do
 case "$1" in
--h|--help)_usage;;
+-h|--help)_usage "$2";;
 -D|--debug)DEBUG="true"&&export DEBUG;;
 -V|--version|--info)_version_info;;
 -l|--log)_check_longoptions "$1" "$2"
@@ -930,7 +1039,7 @@ SKIP_SUBDIRS="true"
 if [[ $2 -gt 0 ]];then
 export NO_OF_PARALLEL_JOBS="$2"
 else
-printf "\nError: -p/--parallel value ranges between 1 to 10.\n"
+printf "\nError: -p/--parallel accepts values between 1 to 10.\n"
 exit 1
 fi
 export PARALLEL_DOWNLOAD="parallel"&&shift
@@ -1037,7 +1146,8 @@ main(){
 [[ $# == 0 ]]&&_short_help
 [[ -z $SELF_SOURCE ]]&&{
 export UTILS_FOLDER="${UTILS_FOLDER:-$PWD}"
-{ . "$UTILS_FOLDER"/auth-utils.bash&&. "$UTILS_FOLDER"/common-utils.bash&&. "$UTILS_FOLDER"/drive-utils.bash&&. "$UTILS_FOLDER"/download-utils.bash;}||{ printf "Error: Unable to source util files.\n"&&exit 1;}
+export COMMON_UTILS_FILE="${COMMON_UTILS_FILE:-$PWD/../common/utils.sh}"
+{ . "$COMMON_UTILS_FILE"&&. "$UTILS_FOLDER"/auth-utils.bash&&. "$UTILS_FOLDER"/common-utils.bash&&. "$UTILS_FOLDER"/drive-utils.bash&&. "$UTILS_FOLDER"/download-utils.bash;}||{ printf "Error: Unable to source util files.\n"&&exit 1;}
 }
 _check_bash_version&&set -o errexit -o noclobber -o pipefail
 _setup_arguments "$@"||exit 1
