Add flag to use aria2c as downloader
* -aria/--aria-flags

	Use aria2c to download. "-aria" doesn't take arguments.

        To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'

	aria can only resume downloads if either --key or --oatuh flag is used.

* Not using aria2c progress bar for now, will see it later. Kinda messes up output

* Change test.sh to test with aria and change workflow to install aria2

* change speed flag to use only K and M.

* remove .aria2 file if present

Fix https://github.com/Akianonymus/gdrive-downloader/issues/11

diff --git a/bash/release/gdl b/bash/release/gdl
--- a/bash/release/gdl
+++ b/bash/release/gdl
@@ -123,8 +123,9 @@ chmod u-w+r "$config_path"
 }
 _download_file(){
 [[ $# -lt 3 ]]&&printf "%s: Missing arguments\n" "${FUNCNAME[0]}"&&return 1
-declare file_id="$1" name="$2" server_size="$3" parallel="$4"
-declare range status old_status left downloaded
+declare file_id="$1" name="$2" server_size="$3" parallel="$4" \
+range status old_status left downloaded use_aria="$DOWNLOAD_WITH_ARIA" \
+flag flag_value url cookies
 server_size_readable="$(_bytes_to_human "$server_size")"
 _print_center "justify" "$name" " | ${server_size:+$server_size_readable}" "="
 if [[ -s $name ]];then
@@ -136,33 +137,42 @@ return 0
 else
 _print_center "justify" "File is partially" " present, resuming.." "-"
 range="Range: bytes=$local_size-$server_size"
+[[ -z ${OAUTH_ENABLED:-$API_KEY_DOWNLOAD} ]]&&unset use_aria
 fi
 else
-range="Range: bytes=0-$server_size"
+[[ $server_size -gt 0 ]]&&range="Range: bytes=0-$server_size"
 _print_center "justify" "Downloading file.." "-"
 fi
 if [[ -n $OAUTH_ENABLED ]];then
 . "${TMPFILE}_ACCESS_TOKEN"
-curl -Ls $CURL_SPEED \
--H "$range" \
--H "Authorization: Bearer $ACCESS_TOKEN" \
-"$API_URL/drive/$API_VERSION/files/$file_id?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true" >>"$name"&
-pid="$!"
+flag="--header" flag_value="Authorization: Bearer $ACCESS_TOKEN"
+url="$API_URL/drive/$API_VERSION/files/$file_id?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true"
 elif [[ -n $API_KEY_DOWNLOAD ]];then
-curl -Ls $CURL_SPEED \
--H "$range" \
--e "https://drive.google.com" \
-"$API_URL/drive/$API_VERSION/files/$file_id?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true&key=$API_KEY" >>"$name"&
-pid="$!"
+flag="--referer" flag_value="https://drive.google.com"
+url="$API_URL/drive/$API_VERSION/files/$file_id?alt=media&supportsAllDrives=true&includeItemsFromAllDrives=true&key=$API_KEY"
 else
 "$EXTRA_LOG" "justify" "Fetching" " cookies.." "-"
-curl -c "$TMPFILE"COOKIE -I $CURL_PROGRESS -o /dev/null "https://drive.google.com/uc?export=download&id=$file_id"||:
+curl -c "${TMPFILE}_${file_id}_COOKIE" -I $CURL_PROGRESS -o /dev/null "https://drive.google.com/uc?export=download&id=$file_id"||:
 for _ in 1 2;do _clear_line 1;done
-confirm_string="$(: "$(grep -F 'download_warning' "$TMPFILE"COOKIE)"&&printf "%s\n" "${_//*$'\t'/}")"||:
-curl -Ls $CURL_SPEED \
--H "$range" \
--b "$TMPFILE"COOKIE \
-"https://drive.google.com/uc?export=download&id=$file_id${confirm_string:+&confirm=$confirm_string}" >>"$name"&
+confirm_string="$(: "$(grep -F 'download_warning' "${TMPFILE}_${file_id}_COOKIE")"&&printf "%s\n" "${_//*$'\t'/}")"||:
+flag="-b" flag_value="${TMPFILE}_${file_id}_COOKIE"
+[[ -n $use_aria ]]&&{
+cookies="$(sed -e "s/^\# .*//g" -e "s/^\#HttpOnly_//g" "${TMPFILE}_${file_id}_COOKIE")"
+printf "%s\n" "$cookies" >|"${TMPFILE}_${file_id}_COOKIE"
+flag="--load-cookies"
+}
+url="https://drive.google.com/uc?export=download&id=$file_id${confirm_string:+&confirm=$confirm_string}"
+fi
+if [[ -n $use_aria ]];then
+aria2c ${SPEED_LIMIT:+$ARIA_SPEED_LIMIT_FLAG} $SPEED_LIMIT $ARIA_EXTRA_FLAGS \
+"$flag" "$flag_value" \
+"$url" -o "$name"&
+pid="$!"
+else
+curl ${SPEED_LIMIT:+$CURL_SPEED_LIMIT_FLAG} $SPEED_LIMIT $CURL_EXTRA_FLAGS \
+--header "$range" \
+"$flag" "$flag_value" \
+"$url" >>"$name"&
 pid="$!"
 fi
 if [[ -n $parallel ]];then
@@ -184,6 +194,7 @@ fi
 if [[ $(wc -c <"$name") -ge $server_size ]];then
 for _ in 1 2;do _clear_line 1;done
 "${QUIET:-_print_center}" "justify" "Downloaded" "="&&_newline "\n"
+rm -f "$name.aria2"
 else
 "${QUIET:-_print_center}" "justify" "Error: Incomplete" " download." "=" 1>&2
 return 1
@@ -380,6 +391,11 @@ printf "%b" "
 The script can be used to download file/directory from google drive.\n
 Usage:\n ${0##*/} [options.. ] <file_[url|id]> or <folder[url|id]>\n
 Options:\n
+  -aria | --aria-flags 'flags' - Use aria2c to download. '-aria' does not take arguments.\n
+      To give custom flags as argument, use long flag, --aria-flags. e.g: --aria-flags '-s 10 -x 10'\n
+      Note 1: aria2c can only resume google drive downloads if '-k/--key' or '-o/--oauth' option is used, otherwise, it will use curl.\n
+      Note 2: aria split downloading won't work in normal mode ( without '-k' or '-o' flag ) because it cannot get the remote server size. Same for any other feature which uses remote server size.\n
+      Note 3: By above notes, conclusion is, aria is basically same as curl in normal mode, so it is recommended to be used only with '--key' and '--oauth' flag.\n
   -o | --oauth - Use this flag to trigger oauth authentication.\n
       Note: If both --oauth and --key flag is used, --oauth flag is preferred.\n
   -k | --key 'API KEY' ( optional arg ) - To download with api key. If api key is not specified, then the predefined api key will be used.\n
@@ -390,7 +406,7 @@ Options:\n
   -d | --directory 'foldername' - option to _download given input in custom directory.\n
   -s | --skip-subdirs - Skip downloading of sub folders present in case of folders.\n
   -p | --parallel 'no_of_files_to_parallely_upload' - Download multiple files in parallel.\n
-  --speed 'speed' - Limit the download speed, supported formats: 1K, 1M and 1G.\n
+  --speed 'speed' - Limit the download speed, supported formats: 1K and 1M.\n
   -R | --retry 'num of retries' - Retry the file upload if it fails, postive integer as argument. Currently only for file uploads.\n
   -l | --log 'file_to_save_info' - Save downloaded files info to the given filename.\n
   -q | --quiet - Supress the normal output, only show success/error upload messages for files, and one extra line at the beginning for folder showing no. of files and sub folders.\n
@@ -443,9 +459,11 @@ exit 0
 _setup_arguments(){
 [[ $# == 0 ]]&&printf "%s: Missing arguments\n" "${FUNCNAME[0]}"&&return 1
 unset LOG_FILE_ID OAUTH_ENABLED API_KEY_DOWNLOAD CONFIG FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD
-unset DEBUG QUIET VERBOSE VERBOSE_PROGRESS SKIP_INTERNET_CHECK RETRY
+unset DOWNLOAD_WITH_ARIA ARIA_EXTRA_FLAGS ARIA_SPEED_LIMIT_FLAG
+unset DEBUG QUIET VERBOSE VERBOSE_PROGRESS SKIP_INTERNET_CHECK RETRY SPEED_LIMIT
 unset ID_INPUT_ARRAY FINAL_INPUT_ARRAY
-CURL_PROGRESS="-s" EXTRA_LOG=":"
+CURL_PROGRESS="-s" CURL_SPEED_LIMIT_FLAG="--limit-rate" CURL_EXTRA_FLAGS="-Ls"
+EXTRA_LOG=":"
 CONFIG="$HOME/.gdl.conf"
 API_KEY="AIzaSyD2dHsZJ9b4OXuy5B_owiL8W18NaNOM8tk"
 API_URL="https://www.googleapis.com"
@@ -466,6 +484,12 @@ case "$1" in
 --info)_info;;
 -l|--log)_check_longoptions "$1" "$2"
 LOG_FILE_ID="$2"&&shift
+;;
+-aria|--aria-flags)DOWNLOAD_WITH_ARIA="true"
+[[ $1 == "--aria-flags" ]]&&{
+_check_longoptions "$1" "$2"
+ARIA_EXTRA_FLAGS=" $ARIA_EXTRA_FLAGS $2 "&&shift
+}
 ;;
 -o|--oauth)OAUTH_ENABLED="true";;
 -k|--key)API_KEY_DOWNLOAD="true"
@@ -493,11 +517,11 @@ fi
 PARALLEL_DOWNLOAD="parallel"&&shift
 ;;
 --speed)_check_longoptions "$1" "$2"
-regex='^([0-9]+)([k,K]|[m,M]|[g,G])+$'
+regex='^([0-9]+)([k,K]|[m,M])+$'
 if [[ $2 =~ $regex ]];then
-CURL_SPEED="--limit-rate $2"&&shift
+SPEED_LIMIT="$2"&&shift
 else
-printf "Error: Wrong speed limit format, supported formats: 1K , 1M and 1G\n" 1>&2
+printf "Error: Wrong speed limit format, supported formats: 1K and 1M.\n" 1>&2
 exit 1
 fi
 ;;
@@ -526,6 +550,11 @@ shift
 done
 [[ -z ${ID_INPUT_ARRAY[*]} ]]&&_short_help
 [[ -n $OAUTH_ENABLED ]]&&unset API_KEY_DOWNLOAD
+[[ -n $DOWNLOAD_WITH_ARIA ]]&&{
+command -v aria2c 1>|/dev/null||{ printf "%s\n" "Error: aria2c not installed."&&exit 1;}
+ARIA_SPEED_LIMIT_FLAG="--max-download-limit"
+ARIA_EXTRA_FLAGS="$ARIA_EXTRA_FLAGS -q --file-allocation=none --auto-file-renaming=false --continue"
+}
 _check_debug
 return 0
 }
@@ -637,7 +666,8 @@ return 0
 _process_arguments(){
 export DEBUG LOG_FILE_ID VERBOSE API_KEY API_URL API_VERSION \
 FOLDERNAME SKIP_SUBDIRS NO_OF_PARALLEL_JOBS PARALLEL_DOWNLOAD SKIP_INTERNET_CHECK \
-COLUMNS CURL_SPEED TMPFILE CURL_PROGRESS EXTRA_LOG RETRY QUIET \
+COLUMNS TMPFILE CURL_PROGRESS EXTRA_LOG RETRY QUIET SPEED_LIMIT \
+DOWNLOAD_WITH_ARIA ARIA_EXTRA_FLAGS ARIA_SPEED_LIMIT_FLAG CURL_SPEED_LIMIT_FLAG CURL_EXTRA_FLAGS \
 OAUTH_ENABLED API_KEY_DOWNLOAD
 export -f _bytes_to_human _count _api_request _api_request_oauth _json_value _print_center _print_center _newline _clear_line \
 _download_file _download_file_main _download_folder _log_in_file
